import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { A2UICatalog, ChatTheme } from '../types';

export type Role = 'system' | 'user' | 'assistant' | 'tool';
export type HITLStatus = 'none' | 'pending' | 'approved' | 'rejected';

export interface ISessionMetadata {
  tags?: string[];
  summary?: string;
  isPinned?: boolean;
  [key: string]: any;
}

export interface ChatSession {
  id: string;
  userId?: string;
  title: string;
  model: string;
  systemStore?: string;
  metadata: ISessionMetadata;
  createdAt: Date | string;
  updatedAt: Date | string;
  messages?: ChatMessage[];
}

export interface A2UIPayload {
  name: string;             // Must match a key in the A2UICatalog
  props: Record<string, any>;
}

export interface ToolCall {
  id: string;               // Unique ID for the tool call (generated by the LLM)
  type: 'function';
  function: {
    name: string;
    arguments: string;      // JSON string of arguments
  };
}

export interface PendingAction {
  toolCallId: string;
  actionName: string;
  description?: string;
  unsafePayload: any;       // The raw payload needing human review
}

export interface ChatMessage {
  id: string;
  sessionId: string;
  role: Role;
  content: string;          // Can be empty if the message is purely a tool call/UI render

  // Adaptive UI
  componentPayload?: A2UIPayload;

  // Tool Execution
  toolCalls?: ToolCall[];
  toolCallId?: string;      // Required if role === 'tool'

  // Security & Interruption
  hitlStatus: HITLStatus;
  pendingAction?: PendingAction;

  createdAt: Date | string;
}

interface AIChatState {
  catalog: A2UICatalog;
  theme: ChatTheme;
  sessionStorageMode: 'memory' | 'api';
  sessionRoute: string;
  includeBasicCatalog: boolean;
  a2uiToolName: string;
  a2uiVersion: 'V0.8' | 'V0.9' | 'V0.9.1' | 'V1.0';
  setCatalog: (catalog: A2UICatalog) => void;
  setTheme: (theme: ChatTheme) => void;
  setSessionStorageMode: (mode: 'memory' | 'api') => void;
  setSessionRoute: (endpoint: string) => void;
  setIncludeBasicCatalog: (include: boolean) => void;
  setA2uiToolName: (name: string) => void;
  setA2uiVersion: (version: 'V0.8' | 'V0.9' | 'V0.9.1' | 'V1.0') => void;
  
  pendingHITLAction: any | null;
  setPendingHITLAction: (action: any | null) => void;
  
  resumeExecution: (result: { status: 'approved' | 'rejected'; payload?: any; reason?: string }) => void;
  setResumeExecution: (fn: (result: any) => void) => void;

  sessions: ChatSession[];
  activeSessionId: string | null;
  setSessions: (sessions: ChatSession[]) => void;
  setActiveSessionId: (id: string | null) => void;
  addSession: (session: ChatSession) => void;
  removeSession: (id: string) => void;
  updateSessionMessages: (id: string, messages: any[]) => void;
}
export const useAIChatStore = create<AIChatState>()(
  persist(
    (set, get) => ({
      catalog: {},
      theme: 'standard',
      sessionStorageMode: 'memory',
      sessionRoute: '/session',
      includeBasicCatalog: false,
      a2uiToolName: 'renderComponent',
      a2uiVersion: 'V0.9', // Default version
      setCatalog: (catalog) => set({ catalog }),
      setTheme: (theme) => set({ theme }),
      setSessionStorageMode: (mode) => set({ sessionStorageMode: mode }),
      setSessionRoute: (endpoint) => set({ sessionRoute: endpoint }),
      setIncludeBasicCatalog: (include) => set({ includeBasicCatalog: include }),
      setA2uiToolName: (name) => set({ a2uiToolName: name }),
      setA2uiVersion: (version) => set({ a2uiVersion: version }),
      
      pendingHITLAction: null,
      setPendingHITLAction: (action) => set({ pendingHITLAction: action }),
      
      resumeExecution: () => {},
      setResumeExecution: (fn) => set({ resumeExecution: fn }),
    
      sessions: [],
      activeSessionId: null,
      setSessions: (sessions) => set({ sessions }),
      setActiveSessionId: (activeSessionId) => set({ activeSessionId }),
      addSession: (session) => set((state) => {
        if (state.sessionStorageMode === 'api') {
          fetch(state.sessionRoute, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(session)
          }).catch(console.error);
        }
        return { sessions: [session, ...state.sessions] };
      }),
      removeSession: (id) => set((state) => {
        if (state.sessionStorageMode === 'api') {
          fetch(`${state.sessionRoute}/${id}`, {
            method: 'DELETE'
          }).catch(console.error);
        }
        return { 
          sessions: state.sessions.filter(s => s.id !== id),
          activeSessionId: state.activeSessionId === id ? null : state.activeSessionId 
        };
      }),
      updateSessionMessages: (id, messages) => set((state) => {
        const mappedMessages: ChatMessage[] = messages.map((m: any) => {
          let componentPayload: A2UIPayload | undefined = undefined;
          let toolCalls: ToolCall[] | undefined = undefined;
          
          if (m.toolInvocations && m.toolInvocations.length > 0) {
            toolCalls = m.toolInvocations.map((t: any) => ({
              id: t.toolCallId,
              type: 'function',
              function: {
                name: t.toolName,
                arguments: typeof t.args === 'string' ? t.args : JSON.stringify(t.args || {})
              }
            }));
            
            const renderComponentTool = m.toolInvocations.find((t: any) => t.toolName === state.a2uiToolName);
            if (renderComponentTool) {
               componentPayload = {
                 name: renderComponentTool.args?.componentName || renderComponentTool.args?.name || renderComponentTool.toolName,
                 props: renderComponentTool.args?.props || renderComponentTool.args || {}
               };
            }
          }

          return {
            id: m.id,
            sessionId: id,
            role: (m.role === 'function' || m.role === 'data') ? 'assistant' : m.role,
            content: m.content || '',
            componentPayload,
            toolCalls,
            hitlStatus: 'none', 
            createdAt: m.createdAt || new Date(),
          };
        });

        const updatedSessions = state.sessions.map(s => s.id === id ? { ...s, messages: mappedMessages } : s);
        
        // Also update API if needed
        if (state.sessionStorageMode === 'api') {
          const sessionToUpdate = updatedSessions.find(s => s.id === id);
          if (sessionToUpdate) {
            fetch(`${state.sessionRoute}/${id}`, {
              method: 'PUT',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(sessionToUpdate)
            }).catch(console.error);
          }
        }
        
        return { sessions: updatedSessions };
      }),
    }),
    {
      name: 'omnichat-storage',
      storage: createJSONStorage(() => typeof window !== 'undefined' ? sessionStorage : ({} as any)),
      partialize: (state) => ({
        // Only persist sessions and activeSessionId if we are in 'memory' mode
        sessions: state.sessionStorageMode === 'memory' ? state.sessions : [],
        activeSessionId: state.sessionStorageMode === 'memory' ? state.activeSessionId : null
      }),
    }
  )
);
