import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { A2UICatalog, ApiSchema, ChatTheme, StorageMode, A2UIProps, AGUIAction } from '../types';

/** Allowed roles in a conversation. */
export type Role = 'system' | 'user' | 'assistant' | 'tool';
/** Statuses for a human-in-the-loop interruption. */
export type HITLStatus = 'none' | 'pending' | 'approved' | 'rejected';

/** Metadata structure for a chat session. */
export interface ISessionMetadata {
  tags?: string[];
  summary?: string;
  isPinned?: boolean;
  [key: string]: any;
}

/** Represents a complete chat conversation. */
export interface ChatSession {
  id: string;
  userId?: string;
  title: string;
  model: string;
  systemStore?: string;
  metadata: ISessionMetadata;
  createdAt: Date | string;
  updatedAt: Date | string;
  messages?: ChatMessage[];
}

/** Describes a component render payload from the Agentic UI. */
export interface A2UIPayload {
  /** The component name, matching an entry in the A2UICatalog. */
  name: string;             
  /** The props to pass to the component. */
  props: Record<string, any>;
}

/** Represents a tool call made by the LLM. */
export interface ToolCall {
  /** Unique ID for the tool call (generated by the LLM). */
  id: string;               
  type: 'function';
  function: {
    name: string;
    /** JSON string of arguments. */
    arguments: string;      
  };
}

/** Represents an action waiting for human approval. */
export interface PendingAction {
  toolCallId: string;
  actionName: string;
  description?: string;
  /** The raw payload needing human review. */
  unsafePayload: any;       
}

/** Defines a single message within a chat session. */
export interface ChatMessage {
  id: string;
  sessionId: string;
  role: Role;
  /** Can be empty if the message is purely a tool call/UI render. */
  content: string;          

  // Adaptive UI
  componentPayload?: A2UIPayload;

  // Tool Execution
  toolCalls?: ToolCall[];
  /** Required if role === 'tool'. */
  toolCallId?: string;      

  // Security & Interruption
  hitlStatus: HITLStatus;
  pendingAction?: PendingAction;

  createdAt: Date | string;
}

/** Partial update object for a session. */
export type SessionUpdate = Partial<Omit<ChatSession, 'id' | 'createdAt' | 'metadata'>> & {
  metadata?: Partial<ISessionMetadata>;
};

const sessionWriteQueues = new Map<string, Promise<unknown>>();
let pendingSessionCreation: Promise<ChatSession> | null = null;

const enqueueSessionWrite = <T,>(id: string, write: () => Promise<T>): Promise<T> => {
  const previous = sessionWriteQueues.get(id) ?? Promise.resolve();
  const next = previous.catch(() => undefined).then(write);
  const queued = next.then(() => undefined, () => undefined);

  sessionWriteQueues.set(id, queued);
  void queued.finally(() => {
    if (sessionWriteQueues.get(id) === queued) {
      sessionWriteQueues.delete(id);
    }
  });

  return next;
};

const sortSessions = (sessions: ChatSession[]) => [...sessions].sort((first, second) => {
  const pinOrder = Number(Boolean(second.metadata?.isPinned)) - Number(Boolean(first.metadata?.isPinned));
  if (pinOrder !== 0) return pinOrder;

  return new Date(second.updatedAt).getTime() - new Date(first.updatedAt).getTime();
});

const upsertSession = (sessions: ChatSession[], session: ChatSession) => {
  const existingIndex = sessions.findIndex((candidate) => candidate.id === session.id);
  const nextSessions = existingIndex === -1
    ? [session, ...sessions]
    : sessions.map((candidate) => candidate.id === session.id ? session : candidate);

  return sortSessions(nextSessions);
};

const parseJsonResponse = async <T,>(response: Response): Promise<T | undefined> => {
  if (!response.ok) {
    throw new Error(`Session request failed: ${response.status} ${response.statusText}`);
  }

  if (response.status === 204 || response.headers.get('content-length') === '0') {
    return undefined;
  }

  const contentType = response.headers.get('content-type');
  if (!contentType?.includes('application/json')) return undefined;

  const body = await response.text();
  return body ? JSON.parse(body) as T : undefined;
};

const toStoredMessages = (messages: any[], sessionId: string, a2uiToolName: string): ChatMessage[] => messages.map((message: any) => {
  let componentPayload: A2UIPayload | undefined;
  let toolCalls: ToolCall[] | undefined;

  if (message.toolInvocations?.length > 0) {
    toolCalls = message.toolInvocations.map((tool: any) => ({
      id: tool.toolCallId,
      type: 'function' as const,
      function: {
        name: tool.toolName,
        arguments: typeof tool.args === 'string' ? tool.args : JSON.stringify(tool.args || {})
      }
    }));

    const renderComponentTool = message.toolInvocations.find((tool: any) => tool.toolName === a2uiToolName);
    if (renderComponentTool) {
      componentPayload = {
        name: renderComponentTool.args?.componentName || renderComponentTool.args?.name || renderComponentTool.toolName,
        props: renderComponentTool.args?.props || renderComponentTool.args || {}
      };
    }
  }

  return {
    id: message.id,
    sessionId,
    role: (message.role === 'function' || message.role === 'data') ? 'assistant' : message.role,
    content: message.content || '',
    componentPayload,
    toolCalls,
    hitlStatus: 'none',
    createdAt: message.createdAt || new Date(),
  } as ChatMessage;
});

const messagesAreEqual = (currentMessages: ChatMessage[] | undefined, nextMessages: ChatMessage[]) => {
  const current = currentMessages || [];
  if (current.length !== nextMessages.length) return false;

  return current.every((message, index) => {
    const next = nextMessages[index];

    return message.id === next.id
      && message.role === next.role
      && message.content === next.content
      && (message.hitlStatus || 'none') === (next.hitlStatus || 'none')
      && JSON.stringify(message.componentPayload || null) === JSON.stringify(next.componentPayload || null)
      && JSON.stringify(message.toolCalls || null) === JSON.stringify(next.toolCalls || null);
  });
};

/**
 * The global Zustand state interface for OmniChatKit.
 */
export interface AIChatState {
  theme: ChatTheme;
  sessionStorageMode: StorageMode;
  sessionRoute: string;
  apiMode: 'classic' | 'ag-ui';
  /** Schema that maps OmniChatKit's internal message format to the backend API (classic mode only). */
  chatApiSchema: ApiSchema | undefined;
  setTheme: (theme: ChatTheme) => void;
  setSessionStorageMode: (mode: StorageMode) => void;
  setSessionRoute: (endpoint: string) => void;
  a2uiProps: A2UIProps | undefined;
  setA2UIProps: (props: A2UIProps) => void;
  setApiMode: (mode: 'classic' | 'ag-ui') => void;
  setChatApiSchema: (schema: ApiSchema | undefined) => void;
  
  pendingHITLAction: any | null;
  setPendingHITLAction: (action: any | null) => void;
  
  resumeExecution: (result: { status: 'approved' | 'rejected'; payload?: any; reason?: string }) => void;
  setResumeExecution: (fn: (result: any) => void) => void;

  sessions: ChatSession[];
  activeSessionId: string | null;
  setSessions: (sessions: ChatSession[]) => void;
  setActiveSessionId: (id: string | null) => void;
  loadSessions: () => Promise<ChatSession[]>;
  getSession: (id: string) => Promise<ChatSession | undefined>;
  createSession: (session: ChatSession) => Promise<ChatSession>;
  ensureSession: (firstMessage: string, fallbackSessionId?: string) => Promise<string | undefined>;
  replaceSession: (id: string, session: ChatSession) => Promise<ChatSession | undefined>;
  updateSession: (id: string, update: SessionUpdate) => Promise<ChatSession | undefined>;
  renameSession: (id: string, title: string) => Promise<ChatSession | undefined>;
  setSessionPinned: (id: string, isPinned: boolean) => Promise<ChatSession | undefined>;
  removeSession: (id: string) => Promise<void>;
  updateSessionMessages: (id: string, messages: any[]) => Promise<ChatSession | undefined>;
  actions: Record<string, AGUIAction>;
  registerAction: (action: AGUIAction) => void;
  unregisterAction: (name: string) => void;
}
export const useAIChatStore = create<AIChatState>()(
  persist(
    (set, get) => ({
      theme: 'standard',
      sessionStorageMode: 'disabled',
      sessionRoute: '/session',
      apiMode: 'classic',
      chatApiSchema: undefined,
      setTheme: (theme) => set({ theme }),
      setSessionStorageMode: (mode) => set(mode === 'disabled'
        ? { sessionStorageMode: mode, sessions: [], activeSessionId: null }
        : { sessionStorageMode: mode }
      ),
      setSessionRoute: (endpoint) => set({ sessionRoute: endpoint }),
      a2uiProps: undefined,
      setA2UIProps: (props) => set({ a2uiProps: props }),
      setApiMode: (mode) => set({ apiMode: mode }),
      setChatApiSchema: (schema) => set({ chatApiSchema: schema }),
      
      pendingHITLAction: null,
      setPendingHITLAction: (action) => set({ pendingHITLAction: action }),
      
      resumeExecution: () => {},
      setResumeExecution: (fn) => set({ resumeExecution: fn }),
    
      actions: {},
      registerAction: (action) => set((state) => ({ actions: { ...state.actions, [action.name]: action } })),
      unregisterAction: (name) => set((state) => {
        const newActions = { ...state.actions };
        delete newActions[name];
        return { actions: newActions };
      }),

      sessions: [],
      activeSessionId: null,
      setSessions: (sessions) => {
        if (get().sessionStorageMode === 'disabled') return;
        set({ sessions: sortSessions(sessions) });
      },
      setActiveSessionId: (activeSessionId) => {
        if (get().sessionStorageMode === 'disabled') return;
        set({ activeSessionId });
      },
      loadSessions: async () => {
        const state = get();
        if (state.sessionStorageMode === 'disabled') return [];
        if (state.sessionStorageMode !== 'api') return state.sessions;

        const response = await fetch(state.sessionRoute);
        const sessions = await parseJsonResponse<ChatSession[]>(response);
        if (!Array.isArray(sessions)) {
          throw new Error('Expected the session list endpoint to return a JSON array.');
        }

        if (get().sessionStorageMode !== 'disabled') {
          set({ sessions: sortSessions(sessions) });
        }
        return sessions;
      },
      getSession: async (id) => {
        const state = get();
        if (state.sessionStorageMode === 'disabled') return undefined;
        const localSession = state.sessions.find((session) => session.id === id);
        if (state.sessionStorageMode !== 'api') return localSession;

        const response = await fetch(`${state.sessionRoute}/${id}`);
        if (response.status === 404) {
          set((current) => ({
            sessions: current.sessions.filter((session) => session.id !== id),
            activeSessionId: current.activeSessionId === id ? null : current.activeSessionId,
          }));
          return undefined;
        }
        const session = await parseJsonResponse<ChatSession>(response);
        if (!session) return localSession;

        if (get().sessionStorageMode !== 'disabled') {
          set((current) => ({ sessions: upsertSession(current.sessions, session) }));
        }
        return session;
      },
      createSession: async (session) => {
        const state = get();
        if (state.sessionStorageMode === 'disabled') {
          throw new Error('Session operations are disabled. Set sessionStorageMode to "memory" or "api" to create sessions.');
        }
        const now = new Date();
        const newSession: ChatSession = {
          ...session,
          metadata: session.metadata || {},
          createdAt: session.createdAt || now,
          updatedAt: session.updatedAt || now,
        };

        let savedSession = newSession;
        if (state.sessionStorageMode === 'api') {
          const response = await fetch(state.sessionRoute, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(newSession),
          });
          const serverSession = await parseJsonResponse<ChatSession>(response);
          if (serverSession) {
            savedSession = {
              ...newSession,
              ...serverSession,
              metadata: { ...newSession.metadata, ...serverSession.metadata },
            };
          }
        }

        if (get().sessionStorageMode !== 'disabled') {
          set((current) => ({ sessions: upsertSession(current.sessions, savedSession) }));
        }
        return savedSession;
      },
      ensureSession: async (firstMessage, fallbackSessionId) => {
        if (get().sessionStorageMode === 'disabled') return undefined;

        const currentSessionId = get().activeSessionId ?? fallbackSessionId;
        if (currentSessionId) {
          if (!get().activeSessionId) set({ activeSessionId: currentSessionId });
          return currentSessionId;
        }

        if (!pendingSessionCreation) {
          const now = new Date();
          pendingSessionCreation = get().createSession({
            id: typeof crypto !== 'undefined' && crypto.randomUUID
              ? crypto.randomUUID()
              : `session-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
            title: firstMessage.slice(0, 30) || 'New Session',
            model: 'default',
            metadata: {},
            createdAt: now,
            updatedAt: now,
          });
        }

        const creation = pendingSessionCreation;
        try {
          const session = await creation;
          if (get().sessionStorageMode === 'disabled') return undefined;
          set({ activeSessionId: session.id });
          return session.id;
        } finally {
          if (pendingSessionCreation === creation) {
            pendingSessionCreation = null;
          }
        }
      },
      replaceSession: async (id, session) => {
        const state = get();
        if (state.sessionStorageMode === 'disabled') return undefined;
        const currentSession = state.sessions.find((candidate) => candidate.id === id);
        if (!currentSession) return undefined;

        const updatedSession: ChatSession = {
          ...session,
          id,
          metadata: session.metadata || {},
          createdAt: session.createdAt || currentSession.createdAt,
          updatedAt: new Date(),
        };
        set((current) => ({ sessions: upsertSession(current.sessions, updatedSession) }));

        if (state.sessionStorageMode === 'api') {
          await enqueueSessionWrite(id, async () => {
            const response = await fetch(`${state.sessionRoute}/${id}`, {
              method: 'PUT',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(updatedSession),
            });
            await parseJsonResponse<ChatSession>(response);
          });
        }

        return updatedSession;
      },
      updateSession: async (id, update) => {
        if (get().sessionStorageMode === 'disabled') return undefined;
        let currentSession = get().sessions.find((session) => session.id === id);
        if (!currentSession) currentSession = await get().getSession(id);
        if (!currentSession) return undefined;

        const updatedSession: ChatSession = {
          ...currentSession,
          ...update,
          metadata: { ...currentSession.metadata, ...update.metadata },
          updatedAt: new Date(),
        };
        const state = get();
        set((current) => ({ sessions: upsertSession(current.sessions, updatedSession) }));

        if (state.sessionStorageMode === 'api') {
          await enqueueSessionWrite(id, async () => {
            const response = await fetch(`${state.sessionRoute}/${id}`, {
              method: 'PATCH',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(update),
            });
            await parseJsonResponse<ChatSession>(response);
          });
        }

        return updatedSession;
      },
      renameSession: (id, title) => {
        if (get().sessionStorageMode === 'disabled') return Promise.resolve(undefined);
        const trimmedTitle = title.trim();
        if (!trimmedTitle) {
          return Promise.reject(new Error('A session title cannot be empty.'));
        }
        return get().updateSession(id, { title: trimmedTitle });
      },
      setSessionPinned: (id, isPinned) => get().sessionStorageMode === 'disabled'
        ? Promise.resolve(undefined)
        : get().updateSession(id, { metadata: { isPinned } }),
      removeSession: async (id) => {
        const state = get();
        if (state.sessionStorageMode === 'disabled') return;
        if (state.sessionStorageMode === 'api') {
          await enqueueSessionWrite(id, async () => {
            const response = await fetch(`${state.sessionRoute}/${id}`, { method: 'DELETE' });
            await parseJsonResponse(response);
          });
        }

        set((current) => ({
          sessions: current.sessions.filter((session) => session.id !== id),
          activeSessionId: current.activeSessionId === id ? null : current.activeSessionId,
        }));
      },
      updateSessionMessages: async (id, messages) => {
        const state = get();
        if (state.sessionStorageMode === 'disabled') return undefined;
        const currentSession = state.sessions.find((session) => session.id === id);
        if (!currentSession) return undefined;

        const storedMessages = toStoredMessages(messages, id, state.a2uiProps?.a2uiToolName || 'renderComponent');
        if (messagesAreEqual(currentSession.messages, storedMessages)) {
          return currentSession;
        }

        const updatedSession: ChatSession = {
          ...currentSession,
          messages: storedMessages,
          updatedAt: new Date(),
        };
        set((current) => ({ sessions: upsertSession(current.sessions, updatedSession) }));

        if (state.sessionStorageMode === 'api') {
          await enqueueSessionWrite(id, async () => {
            const response = await fetch(`${state.sessionRoute}/${id}`, {
              method: 'PUT',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(updatedSession),
            });
            await parseJsonResponse<ChatSession>(response);
          });
        }

        return updatedSession;
      },
    }),
    {
      name: 'omnichat-storage',
      storage: createJSONStorage(() => typeof window !== 'undefined' ? sessionStorage : {
        getItem: () => null,
        setItem: () => {},
        removeItem: () => {},
      }),
      partialize: (state) => ({
        // Keep memory sessions, but never restore an active selection on reload.
        sessions: state.sessionStorageMode === 'memory' ? state.sessions : [],
        activeSessionId: null
      }),
      merge: (persistedState, currentState) => ({
        ...currentState,
        ...(persistedState as Partial<AIChatState>),
        activeSessionId: null,
      }),
    }
  )
);
